name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Ensure .ssh directory exists
        run: mkdir -p ~/.ssh

      - name: SSH Key
        run: echo "${{ secrets.LIGHTSAIL_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to Lightsail
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
        run: |
          scp -i ~/.ssh/id_ed25519 -r dist/* $LIGHTSAIL_USER@$LIGHTSAIL_HOST:/path/to/deploy
          
